
name: Tag Workflow

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest

    env:
      VAR1: "3"

    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Afficher la valeur de ma variable
        run: echo $VAR1
