name: Tag Workflow

on:
  push:
    tags:
      - '*'

jobs:
  job1:
    runs-on: ubuntu-latest

    env:
      VAR1: "3"

    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Afficher la valeur de ma variable
        run: echo $VAR1


#git tag release2    
#git push origin release1