name: Tag Workflow

on:
  push:
    tags:
      - 'main'

jobs:
  job1:
    runs-on: ubuntu-latest

    env:
      VAR1: "3"

    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Afficher la valeur de ma variable
        run: echo $VAR1

  job2:
    needs: job1
    runs-on: ubuntu-latest

    env:
      VAR2: "5"

    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Afficher la valeur de ma variable
        run: echo $VAR2

  job3:
    needs: job2
    runs-on: ubuntu-latest

    if: failure()

    steps:
      - name: Exécuter si job1 a échoué
        run: echo "Le job1 a échoué"


