name: Mon Workflow

on:
  workflow_dispatch:

env:
  A: "6"  
  B: "8"  

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Vérifier que A est positif
        run: |
          if [ "$A" -le 0 ]; then
            echo "Erreur: A doit être un nombre positif."
            exit 1
          fi
      - name: Checkout du code
        uses: actions/checkout@v2

  job2:
    runs-on: ubuntu-latest

    steps:
      - name: Vérifier que B est positif
        run: |
          if [ "$B" -le 0 ]; then
            echo "Erreur: B doit être un nombre positif."
            exit 1
          fi
      - name: Checkout du code
        uses: actions/checkout@v2
